#!/usr/bin/env bash
# Displays "Holberton School" 10 times  using until
s=1
while [ $s -le 10 ]
do
    echo "Holberton School"
    
    if [ $s -eq 9 ]
    then
       echo "Hi"
    fi
    
     ((s++))
done
