#!/usr/bin/env bash
# Displays the number from 1 to 20 along with bad luch from China, Japan, Itallyl
s=1
while [ $s -le 20 ]
do
    echo $s

    case $s in
	4) echo "bad luck from China"
	   ;;
	8) echo "bad luck from Japan"
	   ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac

     ((s++))
done
