#!/usr/bin/env bash
# Displays the number from 1 to 20 along with bad luch from China, Japan, Itallyl
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"

    minute=1

    while [ $minute -le 59 ]
    do
	echo $minute
	((minute++))
    done

    ((hour++))
done
